# Generated by Django 5.2.3 on 2025-08-18 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_profile_picture_base64"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_picture",
        ),
    ]
