# Generated by Django 5.2.3 on 2025-08-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_age_customuser_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Format AAAA-MM-JJ', null=True, verbose_name='Date de naissance'),
        ),
    ]
