# Generated by Django 5.2.3 on 2025-06-26 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcription", models.TextField()),
                (
                    "date",
                    models.DateTimeField(
                        verbose_name="date du reve enregistré"
                    ),
                ),
                (
                    "image_base64",
                    models.TextField(
                        help_text="Image du rêve encodée en base64",
                        verbose_name="Image en Base64",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
