# Generated by Django 4.2.18 on 2025-07-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_remove_dream_image_base64_dream_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dream",
            name="image_prompt",
        ),
    ]
