# Generated by Django 5.2.3 on 2025-08-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0005_dream_image_base64"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dream",
            name="image",
        ),
    ]
