"""
Django settings for Onyria project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os, sys
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Construction des chemins dans le projet
BASE_DIR = Path(__file__).resolve().parent.parent          # .../DreamProject/
ROOT_DIR = BASE_DIR.parent                                  # racine du dépôt

# Charger le .env à la racine du dépôt (utile en local/prod)
load_dotenv(ROOT_DIR / ".env")

# Contexte tests/CI (GitHub Actions, etc.)
IS_CI_OR_TEST = ("test" in sys.argv) or os.getenv("GITHUB_ACTIONS") == "true" or os.getenv("CI") == "true"

if IS_CI_OR_TEST: os.environ["APP_ENV"] = "test"

# Configuration sécurisée - SECRET_KEY obligatoire (fallback uniquement en CI)
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if IS_CI_OR_TEST:
        SECRET_KEY = "django-insecure-ci-test-only"
    else:
        raise ValueError("SECRET_KEY doit être définie (variable d'environnement ou .env)")

# DEBUG désactivé par défaut, mais activé par défaut en CI/tests pour éviter les blocages de checks stricts
DEBUG = os.getenv("DEBUG", "True" if IS_CI_OR_TEST else "False").lower() == "true"

# Analyse des ALLOWED_HOSTS depuis l'env permettant virgules et/ou espaces, sans schémas
_hosts_raw = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [
    h.strip()
    for h in _hosts_raw.replace("https://", "").replace("http://", "").replace(",", " ").split()
    if h.strip()
]

# En production, ALLOWED_HOSTS ne peut pas être vide (mais OK en tests)
if not DEBUG and not ALLOWED_HOSTS and not IS_CI_OR_TEST:
    raise ValueError("ALLOWED_HOSTS doit être défini quand DEBUG=False")

# Configuration IA et modèles - centralisée pour faciliter la maintenance
AI_CONFIG = {
    # Modèles utilisés
    'WHISPER_MODEL': 'whisper-large-v3-turbo',
    'IMAGE_GENERATION_MODEL': 'mistral-medium-2505',
    'EMOTION_MODEL': 'mistral-small-latest',
    'INTERPRETATION_MODEL': 'mistral-large-latest',
    'THEMES_MODEL': 'mistral-large-latest',
    
    # Paramètres de retry
    'TRANSCRIBE_MAX_RETRIES': 3,
    'TRANSCRIBE_BACKOFF_BASE': 1.5,
    
    # Timeouts et limites
    'DEFAULT_TEMPERATURE': 0.0,
    'API_TIMEOUT': 30,
    
    # Hiérarchies de fallback par modèle
    'FALLBACK_CHAINS': {
        'mistral-large-latest': ['mistral-medium', 'mistral-small-latest', 'open-mistral-7b'],
        'mistral-medium': ['mistral-small-latest', 'open-mistral-7b'],
        'mistral-small-latest': ['open-mistral-7b'],
        'open-mistral-7b': [],
    },

    'ERROR_REASON_KEYWORDS': {
        "quota": ["insufficient_quota", "quota_exceeded", "quota"],
        "rate_limit": ["rate_limit", "too many requests", "429"],
        "timeout": ["timeout", "request timeout"],
    },

    # RÈGLES DE RETRY/FALLBACK CHAT (source de vérité unique)
    'RETRYABLE_STATUS': [408, 429, 500, 502, 503, 504],
    'RETRYABLE_KEYWORDS': [
        "too many requests",
        "rate_limit",
        "service_unavailable",
        "temporarily unavailable",
        "timeout",
        "capacity",
        "service tier capacity",
        "insufficient_quota",
        "quota_exceeded",
        "model_not_found",
    ],
    'CHAT_RETRY_BASE_DELAY_S': 0.5,
    'CHAT_RETRY_MAX_DELAY_S': 3.0,

    # RÈGLES DE RETRY TRANSCRIPTION (source de vérité unique)
    'TRANSCRIBE_RETRYABLE_KEYWORDS': [
        "connection error",
        "connection reset",
        "connection aborted",
        "timeout",
        "temporarily unavailable",
        "service unavailable",
        "tls",
        "ssl",
        "proxy",
        "rate limit",
        "503",
        "502",
        "429",
    ]
}

# Clés API depuis les variables d'environnement
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
MISTRAL_API_KEY = os.getenv("MISTRAL_API_KEY")

# Variable pour détecter le mode test
TESTING = 'test' in sys.argv

# Définition des applications
INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    "diary.apps.DiaryConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    "accounts",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Onyria.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Onyria.wsgi.application'


# Base de données
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuration adaptative : utilise DATABASE_URL si présent, sinon SQLite local
database_url = os.getenv("DATABASE_URL")
if database_url:
    DATABASES = {
        'default': dj_database_url.parse(database_url)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Validation de mot de passe
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalisation
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_TZ = True

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True


# Fichiers statiques (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

# Configuration adaptative des fichiers statiques
if DEBUG:
    # Développement : pas de compression/hashing
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
else:
    # Production : WhiteNoise avec compression
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }

# Emplacement des sources d'assets (dossier 'static' à la racine du repo)
STATICFILES_DIRS = [ BASE_DIR.parent / "static" ]


# Type de clé primaire par défaut
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'  # Modèle personnalisé

LOGIN_REDIRECT_URL = '/diary/record/'
LOGOUT_REDIRECT_URL = 'login'

# CONFIGURATION DES LOGS
# Adapte automatiquement le niveau selon l'environnement :
# - Développement (DEBUG=True) : logs DEBUG pour diagnostic détaillé
# - Production (DEBUG=False) : logs INFO+ pour monitoring essentiel

LOG_LEVEL = 'DEBUG' if DEBUG else 'INFO'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': LOG_LEVEL,  # S'adapte selon DEBUG
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'diary': {
            'handlers': ['console'],
            'level': LOG_LEVEL,  # S'adapte selon DEBUG
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}