name: Branch Protection
on:
  pull_request:
    branches: [pre-production, Production]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check pre-production source
        if: github.base_ref == 'pre-production'
        run: |
          if [ "${{ github.head_ref }}" != "Dev" ]; then
            echo "pre-production ne peut recevoir du code que de Dev"
            echo "Branche source détectée: ${{ github.head_ref }}"
            echo "Branche source autorisée: Dev"
            exit 1
          fi
          echo "Source branch valide pour pre-production (Dev → pre-production)"
      
      - name: Check production source  
        if: github.base_ref == 'Production'
        run: |
          if [ "${{ github.head_ref }}" != "pre-production" ]; then
            echo "Production ne peut recevoir du code que de pre-production"
            echo "Branche source détectée: ${{ github.head_ref }}"
            echo "Branche source autorisée: pre-production"
            exit 1
          fi
          echo "Source branch valide pour Production (pre-production → Production)"
